[program:checkpraia-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/pi/checkpraia/artisan queue:work --sleep=3 --tries=3 --max-time=3600 --memory=256
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=pi
numprocs=1
redirect_stderr=true
stdout_logfile=/home/pi/checkpraia/storage/logs/worker.log
stdout_logfile_maxbytes=10MB
stopwaitsecs=30
